version: '3.12'

services:
  web:
    build: .
    command: >
      sh -c "wait-for-it db:5432 -- wait-for-it redis:6379 -- python manage.py makemigrations &&
           python manage.py migrate &&
           python manage.py configuracoes_iniciais &&
           python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
      - redis
    networks:
      - mynetwork
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=pecas_automotivas
      - SQL_USER=postgres
      - SQL_PASSWORD=admin123
      - SQL_HOST=db  # Certifique-se de usar o nome do serviço do banco de dados
      - SQL_PORT=5432
      - REDIS_HOST=redis

    volumes:
      - uploads:/temp

  db:
    image: postgres
    environment:
      POSTGRES_DB: pecas_automotivas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    networks:
      - mynetwork

  redis:
    image: redis:latest
    networks:
      - mynetwork

  celery:
    build: .
    command:  celery -A pecas_automotivas worker -l info
    depends_on:
      - web
      - redis
    networks:
      - mynetwork
    volumes:
      - uploads:/temp

networks:
  mynetwork:
    driver: bridge

volumes:
  uploads: